### ISSUE TITLE
Dimension problem with RNN_train

### ISSUE THREAD

**Issue by Tato14** [MSKCC-Computational-Pathology/MIL-nature-medicine-2019#10]
I performed some MIL training using resnet101 instead of default resnet34. MIL training goes nicely and I could save `.pth` without problems. Also, I used `--batch-size = 64` because of memory issues. 

I changed the code to use resnet101 in `RNN_train.py` and the batch dimension in line 200 `self.fc1 = nn.Linear(64, ndims)`. However, I'm getting a mismatch size issue:

```
Traceback (most recent call last):
  File "RNN_train.py", line 256, in <module>
    main()
  File "RNN_train.py", line 78, in main
    train_loss, train_fpr, train_fnr = train_single(epoch, embedder, rnn, train_loader, criterion, optimizer)
  File "RNN_train.py", line 110, in train_single
    output, state = rnn(input, state)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "RNN_train.py", line 200, in forward
    input = self.fc1(input)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [64 x 2048], m2: [64 x 128] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290
```

I am not quite sure where the 2048 comes from. Any ideas where the problem could be? Also, I am not sure about what `--ndims 128` means.
Thanks!

**Comment by Tato14** [comment]
Ok, solved changing `self.fc1 = nn.Linear(64, ndims)` to `self.fc1 = nn.Linear(2048, ndims)`. For future issues related to this: the input size 2048 is the output of resnet101 as 512 is the output size of resnet34. You can find the doc [here](https://pytorch.org/hub/pytorch_vision_resnet/)
