### ISSUE TITLE
ValueError: ctypes objects containing pointers cannot be pickled

### ISSUE THREAD

**Issue by YiyuHong** [MSKCC-Computational-Pathology/MIL-nature-medicine-2019#4]
I got error when iter Dataloader like following:

`
Traceback (most recent call last):
  File "D:\PyCharm\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "D:\PyCharm\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\PyCharm\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Projects/Colon/Code/Samsung_Colon_MIL/MIL_train_V2.py", line 244, in <module>
    main()
  File "D:/Projects/Colon/Code/Samsung_Colon_MIL/MIL_train_V2.py", line 86, in main
    probs = inference(epoch, train_loader, model)
  File "D:/Projects/Colon/Code/Samsung_Colon_MIL/MIL_train_V2.py", line 134, in inference
    for input in loader:
  File "D:\Anaconda\envs\Colon_Metastasis\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "D:\Anaconda\envs\Colon_Metastasis\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "D:\Anaconda\envs\Colon_Metastasis\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda\envs\Colon_Metastasis\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda\envs\Colon_Metastasis\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda\envs\Colon_Metastasis\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda\envs\Colon_Metastasis\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
ValueError: ctypes objects containing pointers cannot be pickled
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda\envs\Colon_Metastasis\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda\envs\Colon_Metastasis\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
`

The reason for the error seems like because openslide read WSI as pointer.
Any help?
Thanks in advance

**Comment by YiyuHong** [comment]
The error happens when run on windows OS
I tried train code on Linux without error.

**Comment by Zenobia7** [comment]
@YiyuHong  May I ask what  datasets you are using? I downloaded the test data in SVS format on the Internet, but reported an error when using torch to load data d, as follows:
/usr/bin/python3.6 /home/imdl/workspace/MIL-nature-medicine-2019/MIL_train.py
Traceback (most recent call last):
  File "/home/imdl/workspace/MIL-nature-medicine-2019/MIL_train.py", line 222, in <module>
    main()
  File "/home/imdl/workspace/MIL-nature-medicine-2019/MIL_train.py", line 52, in main
    train_dset = MILdataset(args.train_lib, trans)
  File "/home/imdl/workspace/MIL-nature-medicine-2019/MIL_train.py", line 165, in __init__
    lib = torch.load(libraryfile)
  File "/home/imdl/.local/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/imdl/.local/lib/python3.6/site-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
ValueError: could not convert string to int

**Comment by YiyuHong** [comment]
@15122901359 Did you convert the SVS images into a torch's dictionary format??

The author write the Input data format at the ReadMe  "Input data, whether for training, validation or testing, should be a dictionary stored to disk with torch.save()"

**Comment by Zenobia7** [comment]
I am sorry that you have been restored until now. I have solved the problem according to  author write the Input data format, thank you very much.

**Comment by xhm1014** [comment]
> The error happens when run on windows OS
> I tried train code on Linux without error.

I also encounter the error on windows os, but no error on linux. have you found the reasons about this? thanks

**Comment by smehrvar** [comment]
@YiyuHong Same for me. The problem is only on windows os, no error on linux though. Did you resolve your issue?
